### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by SWHL** [iFLYTEK-CV/EDU-CHEMC#1]
Thanks for your great work!

When can we release Handwritten Chemical Structure Image dataset named EDU-CHEMC?

It has been 7 months since the repo was built.

**Comment by iFLYTEK-CV** [comment]
My apologies for the delay. The EDU-CHEMC database is now available to support the competition on ICDAR2024. You can access the competition site at: https://crocs-ifly-ustc.github.io/crocs/index.html. Once the competition concludes, we will open up the database.

**Comment by SWHL** [comment]
Thanks for your reply, I understand. 

But I am just curious about ICDAR2024. The task of Recognition of Chemical Structures is not in the [ICDAR2024 official site](https://rrc.cvc.uab.es/?ch=27&com=introduction). 

So is this competition organized by you personally?

**Comment by iFLYTEK-CV** [comment]
Please check the site at: https://icdar2024.net/competitions/

**Comment by SWHL** [comment]
Thanks.
